# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cbbffc22c9f45d478692f5b41403cede"
web_directories = [ "web" ]
name = "GeoFlow Redirect"

application_url = "https://geoshop-redirect-plugin.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes"

[auth]
redirect_urls = [
 "https://geoshop-redirect-plugin.onrender.com/auth/callback",
  "https://geoshop-redirect-plugin.onrender.com/auth/shopify/callback",
  "https://geoshop-redirect-plugin.onrender.com/api/auth/callback"
]
