# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2f456b7574090f6ab579a706f9b95ff3"
web_directories = ["web"]
name = "GeoFlow Redirect1"
application_url = "https://geoshop-redirect-plugin.onrender.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes"

[auth]
redirect_urls = [
 "https://geoshop-redirect-plugin.onrender.com/auth/callback",
  "https://geoshop-redirect-plugin.onrender.com/auth/shopify/callback",
  "https://geoshop-redirect-plugin.onrender.com/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
